<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/LuckyStarPspToolkit.Licensing.Authority/LuckyStarPspToolkit.Licensing.Authority.csproj" /><ProjectReference Include="../../src/LuckyStarPspToolkit.Cli/LuckyStarPspToolkit.Cli.csproj" /></ItemGroup></Project>
