<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>lsptool</AssemblyName>
    <RootNamespace>LuckyStarPspToolkit.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LuckyStarPspToolkit.Core/LuckyStarPspToolkit.Core.csproj" />
    <ProjectReference Include="../LuckyStarPspToolkit.Formats/LuckyStarPspToolkit.Formats.csproj" />
  </ItemGroup>
</Project>
