#!/usr/bin/env python3
"""Generate or verify the deterministic Markdown catalog of C# declarations."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

from csharp_symbols import MethodSymbol, scan_methods, scan_types

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/API_REFERENCE.md"


def attached_summary(lines: list[str], start_line: int) -> str:
    """Read the XML summary directly attached to a declaration."""
    cursor = start_line - 2
    while cursor >= 0 and not lines[cursor].strip():
        cursor -= 1
    block: list[str] = []
    while cursor >= 0 and lines[cursor].lstrip().startswith("///"):
        block.append(lines[cursor].strip()[3:].strip())
        cursor -= 1
    text = " ".join(reversed(block))
    match = re.search(r"<summary>\s*(.*?)\s*</summary>", text)
    return match.group(1) if match else "No summary available."


def format_method(symbol: MethodSymbol) -> str:
    """Render a compact documented method signature for Markdown."""
    generic = f"<{', '.join(symbol.type_parameters)}>" if symbol.type_parameters else ""
    parameters = ", ".join(
        f"{parameter.modifier + ' ' if parameter.modifier else ''}{parameter.name}"
        for parameter in symbol.parameters
    )
    result = symbol.return_type or "constructor"
    visibility = symbol.visibility or ("local" if symbol.is_local else "private")
    return f"`{visibility} {result} {symbol.name}{generic}({parameters})`"


def render_reference() -> tuple[str, int, int, int]:
    """Render the complete API reference and return coverage counters."""
    paths = sorted(p for p in (ROOT / "src").rglob("*.cs") if not {"bin", "obj"} & set(p.parts))
    lines = [
        "# C# API and method catalog",
        "",
        "This file is generated by `scripts/generate_api_reference.py`. It catalogs every named type, method, constructor, and local function in runtime source. XML comments in the source remain the authoritative detailed documentation.",
        "",
    ]
    total_types = 0
    total_methods = 0
    for path in paths:
        types = scan_types(path)
        methods = scan_methods(path)
        if not types and not methods:
            continue
        total_types += len(types)
        total_methods += len(methods)
        source_lines = path.read_text(encoding="utf-8-sig").splitlines()
        lines.extend([f"## `{path.relative_to(ROOT).as_posix()}`", ""])
        if types:
            lines.extend(["### Types", ""])
            for symbol in types:
                lines.append(
                    f"- `{symbol.visibility or 'internal'} {symbol.kind} {symbol.name}` — "
                    f"{attached_summary(source_lines, symbol.start_line)}"
                )
            lines.append("")
        if methods:
            lines.extend(["### Methods and functions", ""])
            for symbol in methods:
                lines.append(
                    f"- {format_method(symbol)} — {attached_summary(source_lines, symbol.start_line)}"
                )
            lines.append("")
    lines.extend([
        "## Coverage",
        "",
        f"- Runtime C# files: {len(paths)}",
        f"- Named types: {total_types}",
        f"- Named methods, constructors, and local functions: {total_methods}",
        "",
        "Test-source documentation is validated as part of the release gate but omitted from this public API catalog.",
        "",
    ])
    return "\n".join(lines), len(paths), total_types, total_methods


def main() -> int:
    """Generate the API reference or verify that the committed file is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the committed reference is stale.")
    args = parser.parse_args()
    rendered, files, types, methods = render_reference()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it.")
            return 1
        print(f"API reference is current: {files} files, {types} types, {methods} methods/functions.")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}: {types} types, {methods} methods/functions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
