<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LuckyStarPspToolkit.Core</AssemblyName>
    <RootNamespace>LuckyStarPspToolkit</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA5350;CA5351;CA5358</NoWarn>
  </PropertyGroup>
</Project>
